DROP DATABASE IF EXISTS animals_walk;
CREATE DATABASE IF NOT EXISTS animals_walk;
USE animals_walk;

DROP TABLE IF EXISTS peoples;

CREATE TABLE peoples (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR 20 NOT NULL,
);

CREATE TABLE pets (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR 20 NOT NULL,
  sex CHAR 1 NOT NULL,
  birth DATE NOT NULL,
);

CREATE TABLE walk (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    peoples_id INT FOREIGN KEY NOT NULL,
    pets_id  INT FOREIGN KEY NOT NULL,
).